### ISSUE TITLE
Convert many heic pictures into many jpec ones

### ISSUE THREAD

**Issue by Cras1990** [catdad-experiments/heic-convert#10]
Hi

In one of the examples you give in the manual it is assumed that one single heic file contains many single pictures.

I have following use case:
  - I need to convert many single files, whose file format is heic, inside of one folder into jpeg files. Each of the mentioned heic files does only contain one single image.

I´m javascript beginner and don´t know how to solve this since using your script only one single heic file is converted into multiple jpec files.

Any idea how to solve this by adapting your example script _Convert the main image in a HEIC to PNG_ ?

I look forward to your reply.

Thanks in advance.

Best

Sam

**Comment by catdad** [comment]
Hi Sam. Welcome to programming! I hope you enjoy it.

However, what you are asking doesn't really have anything to do with this library and I cannot provide free consulting. My time is valuable and I hope you can understand that.

Luckily, what you are asking is also quite simple and should be very easy to look up yourself! A first step might be to get comfortable using loops. I wish you good luck
