### ISSUE TITLE
Browser vs Server Side Support

### ISSUE THREAD

**Issue by LeoWW** [catdad-experiments/heic-convert#15]
Hi, was wondering if this library was meant for Server-Side usage or Browser usage? Thanks!

**Comment by catdad** [comment]
It should work fine for both, as long as you are compiling with something webpack/rollup/etc. to provide proper browser fallbacks.

Though, it is worth mentioning that this module is not really optimized for small bundle size for browsers. You might be better off using [`heic-decode`](https://github.com/catdad-experiments/heic-decode) and then encoding the data using canvas. In addition to not bundling some bulky modules, that would also actually work faster than using `jpeg-js` and `pngjs`.
