### ISSUE TITLE
image not convert into JPEG

### ISSUE THREAD

**Issue by jbhandure** [catdad-experiments/heic-convert#19]
[test_osg.zip](https://github.com/catdad-experiments/heic-convert/files/7710399/test_osg.zip)

PFA.

Please help me

**Comment by catdad** [comment]
I am sorry, I am not familiar with "PFA". What are you asking?

Also, you have not included any information about how you are using this module or the behavior that you are seeing (for example: What are you attempting to do? Is there an error? How have you validated that this heic file is a valid file? How was this heic file generated?). Can you please provide some actionable information?
