### ISSUE TITLE
HEIF cannot convert to Jpg

### ISSUE THREAD

**Issue by ChanChiHang** [catdad-experiments/heic-convert#20]
Could not parse HEIF file｛
 code:heif_error_code_heif_error_invalid_input
sub code:heif sub error code heif sub error end of data
}

**Comment by catdad** [comment]
There's no attached file in order to repro this issue, or repro steps. I'm going to close this as invalid. If you still have an issue, please file a new bug or comment back here with a way to reproduce the issue you are seeing.
